---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-secret
  namespace: keycloak
spec:
  encryptedData:
    password: AgBUaoyE8yj0wSCNuVMXPYG9uUycRe1DZXj9GuhMZvxLTm3H+NV9PPMvDSjFDBR4ai3KmxQfbj25rmclwQOH/S57lAlXgOEFln2wIxjyQmzWEynDA4xS8nBTrz/90JkDS4xOv1a9aqP8X+IoEhF+HeobvAl/IVY16za5PcbpXVxKhIYCN+YXCXbNv1+PCn7nDk/15RxNkAZKJrwFXHTXFjq9ONdmsJrOvb10h28Idbym3NoQSeJjAtoiHoNuVkF9/kt22MpJiP0O1fQuqEISdjFCaDkQcaG2Uz9Ghye3+eSBu1lQI9Kc/ivMUsCz8fWKVRnTzcWHykzW0EY6Q9wLDv/Lq9lKTzsQICFvOn785E5PFevTK6kUHOL7irJmXSEJpbDJh5oja2DNMIw5Xh55SKQqn/DYuMrqYdBUTDCltnsjjF/N/6mS76CsW4J4pYbKHTI5w69+hhySAhlQkBPwtoPB9evtf/nBLRkGLm9qZ+rUtJ7+qpCSjLiBdb2GWvecIoaGkYJvxNnK0Lb4eHVS92i8R2tY74LG2tFIBWQrD41+038wp/BSMl93sq6K6NcYI9bQvNQEyclTVySpfQZTlFkcveMjCQF8AWDZnBfz/bY7SJxQCARWSfYEuC8qAUM6pXPVfSstcDgAkVu0SIAzZb+++HJu7gNUcqH3/8xw2IEq7pfsTMgRy/PsXcn9hJVCdAcWbVm7XfV30ACJs3snEcqk5kLwtNAkMETwjDGwQMidWLmrXeaV+Zc8
    username: AgCNcKkqq+ckTsEi6XBoz/wZUupoWrQDq9tkNFH8xDEa3AKLV1oEPMYVQoMPvkFtRd+UAlLXJqE7aENaqvU/w99H/4iOSsofcB08R/LUFQ7FKTQDe1mB6pZMvEGd+5NJIgdnaQqJTuim+IPtrp3FSXsA5u4/wVdZxaKNnT500pO5UVs7jbopllu5dyv/ObfHZTHckYD22ZwzrATDqsMY9/PehyokYpD8KegbwmGVhr8bHjHkGiUSwB7hwjdy3tQ+DFsDQQOC5p+CR2gccVAwIJLcvyFZyPWqpIdYqu338uWXh+Z9gef6to5fRqV4WyH23A9jEu4ToOj/s3+nlCbKEPwRh++P6cWP92y7zbd+TI0sFHff9a6m8aD2D7icEjI0EMZcpPKPjy+NZ5jWQj5wA4547Hke+2G5fuD5+RBGeca/cCfPo3butV4EOxxGWUhpJm1kzdpVklcGTA1tKux67SClPjRfEgAlhF7Ohq7gFjhjWDdFKTrpOWi39tNiepTv3x70EYb+01EPE/yAZzugBMWqx+EYIY8p80T04gXjyUtH7pikIUKK9HXXLjZ22T2GkX/nVD00kjWp+siK13QS9OmswhQLYMqyS4m0P7PW427ZNXFNCZKzl/r49pJVfChRZa2z4G0wbuIxK3B8tKsDBrDSKLKLncdKAc3ro3zQqgkAo93/4+33h2ofyD510wNjlfyhB0eLwt2wxQ==
  template:
    metadata:
      name: keycloak-db-secret
      namespace: keycloak
