---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  namespace: developer-hub
data:
  app-config.yaml: |
    app:
      title: Red Hat Developer Hub

    backend:
      auth:
        externalAccess:
          - type: legacy
            options:
              subject: legacy-default-config
              secret: "${BACKEND_SECRET}"

    auth:
      environment: development
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
