---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-secrets
  namespace: developer-hub
spec:
  encryptedData:
    BACKEND_SECRET: AgAq5NdUMYcq4rJqaXQFYY1NQ0XLqk9EAgUCRBScWs94AQf0KoW7FPdue2k1oSsOffKmCbM+0odH7cOL1AftX1jTY2leZPOOQ7w1ks45HYHW3dSBCKeWln96epC0QIka3ZbMA28rw9fqRGS3gEFAfMGKHfhy9JPKy53+eVcC6dBQg+jZP2uGIvTsygBLObGrbL3+T7feT768rJQwGTNOLMT8n1YzRY9u4SveY6dwpibKbsKC9AtFuLLakZv/HVNJpTyoeqioYBvZd1TdquaEVUXn0R7n80HOShBkVvaCN3IRnsWDRKUmHE27ceSdSy4wY7nrwFSMw5z+5KvXO9WQA9SEQb/y4AD84qfpmnztL44K94wZ0PKFoh326JmbczMINn5l0U+rMdUAKEQc+rcHR6SDQAncJTE2UTshRYIT8Jn1qBJg8bGQi1rbQQSsC3GU0BAuBfUkAXr6Gh8pcAFcX0Tq+Y0mqNxrnRJq7Cu5o+HN/rUC5xrq3EqNan2dHkgOoa/tcCqfBhkVW0h3x2dl/Z1jIgy848Bo/l6FCzsy+yoDO8zE1mv9IfQl8r+mLQJNmwlZmCDYrYuXOR8ZV8DyIk4ShrmVrQeZbDAaIYC5hi9+1xvklJeUNe5HLoiSGTuEZ3YcgKQ5H4qZrd8e119IHIYve8U30c67EBh+S8apztNMzFVF3C0QjFjLwLOzljSRjj8jD/9oWTFxVfqqv3Fve1yWpTB7X+H+hzkGWvy+V/1PBLjRNEoNCIM+9Q2nZPvjvjmGet3uWQ4BkVCLoyWdoFaL
  template:
    metadata:
      name: backstage-secrets
      namespace: developer-hub
