---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: developer-hub-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/Babas10/developer-hub-env
    targetRevision: main
    path: k8s/developer-hub/operator
  destination:
    server: https://kubernetes.default.svc
    namespace: rhdh-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
